image: mirror.gcr.io/jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

before_script:
- export CI=GitLab
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew
- apt-get update
- apt-get install -y openjdk-17-jdk

stages:
- build
- test
- deploy

debug-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-debug$/'
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    reports:
      dotenv: build.env
    paths:
      - $CI_COMMIT_TAG.apk
  script:
    - ./gradlew assembleDebug
    - echo JOB_ID="$CI_JOB_ID" >> build.env
    - mv app/build/outputs/apk/debug/app-universal-debug.apk $CI_COMMIT_TAG.apk

debug-test:
  stage: test
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-debug$/'
  variables:
    JOB_ID: $JOB_ID
    PLATFORM: $PLATFORM
  needs: [debug-build]
  trigger:
    project: qa/ELTA-automation
    branch: master

deploy-debug:
  image: mirror.gcr.io/library/node:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-debug$/'
  needs: [debug-build]
  script:
    - npm install -g firebase-tools
    - TAG_MESSAGE=$(git tag -l --format='%(contents)' $CI_COMMIT_TAG)
    - firebase appdistribution:distribute $CI_COMMIT_TAG.apk --app $FIREBASE_APP_ID
      --release-notes "$TAG_MESSAGE"
      --groups "testGroup"
  after_script:
    - >
      if [ "$CI_JOB_STATUS" == "success" ]; then
        TAG_MESSAGE=$(git tag -l --format='%(contents)' $CI_COMMIT_TAG)
        curl -X POST -H 'Content-type: application/json' --data "{
                  \"text\": \"*Собран билд:* $CI_COMMIT_TAG\n*Инициатор сборки билда:* $GITLAB_USER_NAME\n*Release Notes:* $TAG_MESSAGE\n*Детали билда:* <$CI_JOB_URL|ссылка>\",
                  \"mrkdwn\": true
                }" $CHANNEL_WEB_HOOK;
      fi

release-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-release$/'
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    reports:
      dotenv: build.env
    paths:
      - $CI_COMMIT_TAG.apk
  script:
    - ./gradlew assembleRelease
    - echo JOB_ID="$CI_JOB_ID" >> build.env
    - mv app/build/outputs/apk/release/app-universal-release.apk $CI_COMMIT_TAG.apk

release-app-bundle-manual:
  stage: build
  when: manual
  only:
    - /-release$/
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - $CI_COMMIT_TAG.aab
  script:
    - ./gradlew clean
    - ./gradlew bundleRelease
    - mv app/build/outputs/bundle/release/app-release.aab $CI_COMMIT_TAG.aab

huawei-manual:
  stage: build
  when: manual
  only:
    - /-release$/
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - $CI_COMMIT_TAG-huawei.apk
  script:
    - ./gradlew clean
    - ./gradlew assembleHuawei
    - mv app/build/outputs/apk/huawei/app-universal-huawei.apk $CI_COMMIT_TAG-huawei.apk


release-test:
  stage: test
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-release$/'
  variables:
    JOB_ID: $JOB_ID
    PLATFORM: $PLATFORM
  needs: [release-build]
  trigger:
    project: qa/ELTA-automation
    branch: master

deploy-release:
  image: mirror.gcr.io/library/node:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-release$/'
  needs: [release-build]
  script:
    - npm install -g firebase-tools
    - TAG_MESSAGE=$(git tag -l --format='%(contents)' $CI_COMMIT_TAG)
    - firebase appdistribution:distribute $CI_COMMIT_TAG.apk --app $FIREBASE_APP_ID
      --release-notes "$TAG_MESSAGE"
      --groups "testGroup"
  after_script:
    - >
        if [ "$CI_JOB_STATUS" == "success" ]; then
          TAG_MESSAGE=$(git tag -l --format='%(contents)' $CI_COMMIT_TAG)
          curl -X POST -H 'Content-type: application/json' --data "{
                    \"text\": \"*Собран билд:* $CI_COMMIT_TAG\n*Инициатор сборки билда:* $GITLAB_USER_NAME\n*Release Notes:* $TAG_MESSAGE\n*Детали билда:* <$CI_JOB_URL|ссылка>\",
                    \"mrkdwn\": true
                  }" $CHANNEL_WEB_HOOK;
        fi

