image: jangrewe/gitlab-ci-android

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

before_script:
- export CI=GitLab
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

stages:
- build
- test


debug-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-debug$/'
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - build_apks/
  script:
    - ./gradlew assembleDebug
    - mkdir build_apks
    - mv app/build/outputs/apk/debug/app-universal-debug.apk build_apks/

debug-test:
  stage: test
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-debug$/'
  variables:
    JOB_ID: $JOB_ID
    PLATFORM: $PLATFORM
  needs: [debug-build]
  trigger:
    project: qa/ELTA-automation
    branch: master

release-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-release$/'
  tags:
    - android,docker
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - build_apks/
  script:
    - ./gradlew assembleRelease
    - mkdir build_apks
    - mv app/build/outputs/apk/release/app-universal-release.apk build_apks/

release-test:
  stage: test
  rules:
    - if: '$CI_COMMIT_TAG  =~ /-release$/'
  variables:
    JOB_ID: $JOB_ID
    PLATFORM: $PLATFORM
  needs: [release-build]
  trigger:
    project: qa/ELTA-automation
    branch: master


