allprojects {
    repositories {
        mavenCentral()
    }
}

ext.androidVersions = [
        androidBuildToolsVersion: '29.0.3',
        androidMinSdkVersion    : 24,
        androidTargetSdkVersion : 29,
        androidCompileSdkVersion: 32
]

def libraryVersions = [
        //Support libraries
        supportLibraryVersion      : '28.0.0',
        playServicesVersion        : '16.0.0',
        firebaseVersion            : '16.0.6',
        firebaseMessagingVersion   : '17.3.4',
        firebaseInAppMessaging     : '17.1.1',
        firebaseDynamicLinkVersion : '16.1.5',
        constraintVersion          : '1.1.3',
        customTabsVersion          : '27.1.0',
        androidAnnotationsVersion  : '21.0.3',
        multiDexVersion            : '1.0.3',
        googleFitVersion           : '16.0.1',
        googleAuthVersion           : '16.0.1',

        //Rx Libraries
        rxJavaVersion              : '2.2.5',
        rxKotlinVersion            : '2.4.0',
        rxAndroidVersion           : '2.1.0',
        rxRelay                    : '2.1.0',
        rxLocationVersion          : '2.1@aar',
        rxPermissionsVersion       : '0.10.2',
        rxPmVersion                : '2.1.2',
        rxBindingVersion           : '2.0.0',
        rxNetworkVersion           : '3.0.2',
        rxReplayingVersion         : '2.1.1',

        //Network
        gsonVersion                : '2.8.5',
        okHttpVersion              : '3.12.1',
        retrofitVersion            : '2.5.0',

        //DI
        daggerVersion              : '2.22.1',
        javaxAnnotationVersion     : '1.3.2',
        javaxInjectVersion         : '1',
        glassfishAnnotationVersion : '10.0-b28',

        android310Version          : '1.2.0',
        java310Version             : '1.3.1',
        appCoreVersion             : '2.0.1-beta.2',
        glideVersion               : '4.8.0',
        materialDialogsVersion     : '0.9.4.4',
        timberVersion              : '4.7.1',
        expandableLayoutVersion    : '2.9.2',
        tooltipVersion             : '0.1.9',
        crashlyticsVersion         : '2.9.8@aar',
        inputMaskVersion           : '6.1.0',
        pinViewVersion             : '1.4.4',
        exoPlayer                  : '2.9.0',
        barcodeScannerVersion      : '1.9.8',
        datePickerVersion          : '2.0.0',
        materialEditTextVersion    : '2.1.4',
        mapKitVersion              : '3.3.1',
        mapKitClusteringVersion    : '0.2',
        cardViewVersion            : '1.0.0',
        pulseViewVersion           : '1.0.3',

        // Bluetooth
        nordicScannerVersion       : '1.3.1',
        nordicDfuVersion           : '2.0.3',
        rxBluetoothVersion         : '1.8.2',

        workVersion                : '1.0.1',

        //Testing
        robolectricVersion         : '4.8',
        jUnitVersion               : '4.13.2',
        assertJVersion             : '3.8.0',
        dexmakerVersion            : '1.0',
        espressoVersion            : '3.4.0',
        testingSupportLibVersion   : '0.1',
        mockitoKotlinVersion       : '2.0.0-RC1',
        mockitoAndroidVersion      : '2.8.47',
        androidSupportRunnerVersion: '1.0.0',
        androidSupportRulesVersion : '1.0.0',
        dexmakerMockitoversion     : '2.2.0',
        runnerVersion              : '0.5',

        ciceroneVersion            : '7.1',

        ktlintVersion              : "0.45.2",

        fbVersion                  : '4.29.0',
        vkVersion                  : '1.6.9',
        okVersion                  : '2.1.6',

        jodaTimeVersion            : '2.9.9.2',

        objectboxVersion           : ext.objectboxVersion,

        coroutinesVersion          : '1.3.9'
]

ext.commonDependencies = [
        libs                  : fileTree(dir: 'libs', include: ['*.jar']),
        supportAnnotations    : "com.android.support:support-annotations:${libraryVersions.supportLibraryVersion}",
        supportV4             : "com.android.support:support-v4:${libraryVersions.supportLibraryVersion}",
        supportV13            : "com.android.support:support-v13:${libraryVersions.supportLibraryVersion}",
        supportCompatV7       : "com.android.support:appcompat-v7:${libraryVersions.supportLibraryVersion}",
        supportRecyclerView   : "com.android.support:recyclerview-v7:${libraryVersions.supportLibraryVersion}",
        supportCardView       : "com.android.support:cardview-v7:${libraryVersions.supportLibraryVersion}",
        supportDesign         : "com.android.support:design:${libraryVersions.supportLibraryVersion}",
        supportvectorDrawable : "com.android.support:support-vector-drawable:${libraryVersions.supportLibraryVersion}",
        supportConstraint     : "com.android.support.constraint:constraint-layout:${libraryVersions.constraintVersion}",
        supportCustomTabs     : "com.android.support:customtabs:${libraryVersions.customTabsVersion}",
        multiDex              : "com.android.support:multidex:${libraryVersions.multiDexVersion}",

        rxKotlin              : "io.reactivex.rxjava2:rxkotlin:${libraryVersions.rxKotlinVersion}",
        rxAndroid             : "io.reactivex.rxjava2:rxandroid:${libraryVersions.rxAndroidVersion}",
        rxPm                  : "me.dmdev.rxpm:rxpm:${libraryVersions.rxPmVersion}",
        rxBinding             : "com.jakewharton.rxbinding2:rxbinding-kotlin:${libraryVersions.rxBindingVersion}",
        rxRelay               : "com.jakewharton.rxrelay2:rxrelay:${libraryVersions.rxRelay}",
        rxLocation            : "pl.charmas.android:android-reactive-location2:${libraryVersions.rxLocationVersion}",
        rxPermissions         : "com.github.tbruyelle:rxpermissions:${libraryVersions.rxPermissionsVersion}",
        rxNetwork             : "com.github.pwittchen:reactivenetwork-rx2:${libraryVersions.rxNetworkVersion}",
        rxReplaying           : "com.jakewharton.rx2:replaying-share-kotlin:${libraryVersions.rxReplayingVersion}",

        dagger                : "com.google.dagger:dagger:${libraryVersions.daggerVersion}",
        daggerCompiler        : "com.google.dagger:dagger-compiler:${libraryVersions.daggerVersion}",
        daggerAndroid         : "com.google.dagger:dagger-android:${libraryVersions.daggerVersion}",
        daggerAndroidProcessor: "com.google.dagger:dagger-android-processor:${libraryVersions.daggerVersion}",
        daggerAndroidSupport  : "com.google.dagger:dagger-android-support:${libraryVersions.daggerVersion}",

        javaxAnnotation       : "javax.annotation:javax.annotation-api:${libraryVersions.javaxAnnotationVersion}",
        javaxInject           : "javax.inject:javax.inject:${libraryVersions.javaxInjectVersion}",
        glassfish             : "org.glassfish:javax.annotation:${libraryVersions.glassfishAnnotationVersion}",

        retrofit              : "com.squareup.retrofit2:retrofit:${libraryVersions.retrofitVersion}",
        retrofitConverter     : "com.squareup.retrofit2:converter-gson:${libraryVersions.retrofitVersion}",
        retrofitAdapter       : "com.squareup.retrofit2:adapter-rxjava2:${libraryVersions.retrofitVersion}",

        okHttp                : "com.squareup.okhttp3:okhttp:${libraryVersions.okHttpVersion}",
        okHttpLogger          : "com.squareup.okhttp3:logging-interceptor:${libraryVersions.okHttpVersion}",

//        appCore               : "com.nullgr.core:core-all:${libraryVersions.appCoreVersion}",
//        appCoreInteractor     : "com.nullgr.core:core-interactor:${libraryVersions.appCoreVersion}",
//        appCoreRx             : "com.nullgr.core:core-rx:${libraryVersions.appCoreVersion}",
//        appCoreIntents        : "com.nullgr.core:core-intents:${libraryVersions.appCoreVersion}",
//        appCoreAdapterKtx     : "com.nullgr.core:core-adapter-ktx:${libraryVersions.appCoreVersion}",
//        appCoreSecurity       : "com.nullgr.core:core-security:${libraryVersions.appCoreVersion}",
//        appCoreHardware       : "com.nullgr.core:core-hardware:${libraryVersions.appCoreVersion}",

        jodaTime             : "net.danlew:android.joda:${libraryVersions.jodaTimeVersion}",
        kotlin                : "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlin_version}",
        gson                  : "com.google.code.gson:gson:${libraryVersions.gsonVersion}",
        glide                 : "com.github.bumptech.glide:glide:${libraryVersions.glideVersion}",
        glideProcessor        : "com.github.bumptech.glide:compiler:${libraryVersions.glideVersion}",
        crashlytics           : "com.crashlytics.sdk.android:crashlytics:${libraryVersions.crashlyticsVersion}",
        materialDialogs       : "com.afollestad.material-dialogs:core:${libraryVersions.materialDialogsVersion}",
        jsr310                : "com.jakewharton.threetenabp:threetenabp:${libraryVersions.android310Version}",
        picasso               : "com.squareup.picasso:picasso:${libraryVersions.picassoVersion}",
        expandableLayout      : "com.github.cachapa:ExpandableLayout:${libraryVersions.expandableLayoutVersion}",
        tooltipLibrary        : "com.github.vihtarb:tooltip:${libraryVersions.tooltipVersion}",
        timber                : "com.jakewharton.timber:timber:${libraryVersions.timberVersion}",
        inputMask             : "com.github.RedMadRobot:input-mask-android:${libraryVersions.inputMaskVersion}",
        pinView               : "io.github.chaosleung:pinview:${libraryVersions.pinViewVersion}",
        barcodeScanner        : "me.dm7.barcodescanner:zxing:${libraryVersions.barcodeScannerVersion}",
        materialEditText      : "com.rengwuxian.materialedittext:library:${libraryVersions.materialEditTextVersion}",
        yandexMapKit          : "com.yandex.android:mapkit:${libraryVersions.mapKitVersion}",
        yandexMapKitClustering: "com.github.65apps:android-clustering-for-yandex-mapkit:${libraryVersions.mapKitClusteringVersion}",
        cardView              : "com.github.captain-miao:optroundcardview:${libraryVersions.cardViewVersion}",
        pulseView             : "pl.bclogic:pulsator4droid:${libraryVersions.pulseViewVersion}",

        location              : "com.google.android.gms:play-services-location:${libraryVersions.playServicesVersion}",
        maps                  : "com.google.android.gms:play-services-maps:${libraryVersions.playServicesVersion}",
        googleAnalytics       : "com.google.android.gms:play-services-analytics:${libraryVersions.googleAnalyticsVersion}",
        googleFit             : "com.google.android.gms:play-services-fitness:${libraryVersions.googleFitVersion}",
        googleAuth            : "com.google.android.gms:play-services-auth:${libraryVersions.googleAuthVersion}",

        firebaseCore          : "com.google.firebase:firebase-core:${libraryVersions.firebaseVersion}",
        firebaseMessaging     : "com.google.firebase:firebase-messaging:${libraryVersions.firebaseMessagingVersion}",
        firebaseInAppMessaging: "com.google.firebase:firebase-inappmessaging-display:${libraryVersions.firebaseInAppMessaging}",
        firebaseDynamicLinks  : "com.google.firebase:firebase-dynamic-links:${libraryVersions.firebaseDynamicLinkVersion}",

        ktlint                : "com.github.shyiko:ktlint:${libraryVersions.ktlintVersion}",

        cicerone              : "com.github.terrakok:cicerone:${libraryVersions.ciceroneVersion}",
        exoPlayer             : "com.google.android.exoplayer:exoplayer:${libraryVersions.exoPlayer}",
        datePicker            : "com.github.prolificinteractive:material-calendarview:${libraryVersions.datePickerVersion}",

        fb                    : "com.facebook.android:facebook-login:${libraryVersions.fbVersion}",
        vk                    : "com.vk:androidsdk:${libraryVersions.vkVersion}",
        ok                    : "ru.ok:odnoklassniki-android-sdk:${libraryVersions.okVersion}",

        objectbox             : "io.objectbox:objectbox-kotlin:${libraryVersions.objectboxVersion}",
        objectboxBrowser      : "io.objectbox:objectbox-android-objectbrowser:${libraryVersions.objectboxVersion}",

        nordicScanner         : "no.nordicsemi.android.support.v18:scanner:${libraryVersions.nordicScannerVersion}",
        nordicDfu             : "no.nordicsemi.android:dfu:${libraryVersions.nordicDfuVersion}",
        rxBluetooth           : "com.polidea.rxandroidble2:rxandroidble:${libraryVersions.rxBluetoothVersion}",

        // new dependencies
        coroutines            : "org.jetbrains.kotlinx:kotlinx-coroutines-android:${libraryVersions.coroutinesVersion}",
        guavaConfictLost      : "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava"
]

ext.commonTestDependencies = [
        junit          : "junit:junit:${libraryVersions.jUnitVersion}",
        kotlinJUnit    : "org.jetbrains.kotlin:kotlin-test-junit:${kotlin_version}",
        assertj        : "org.assertj:assertj-core:${libraryVersions.assertJVersion}",
        mockito        : "com.nhaarman.mockitokotlin2:mockito-kotlin:${libraryVersions.mockitoKotlinVersion}",
        robolectric    : "org.robolectric:robolectric:${libraryVersions.robolectricVersion}",
        supportRunner  : "com.android.support.test:runner:${libraryVersions.androidSupportRunnerVersion}",
        supportRules   : "com.android.support.test:rules:${libraryVersions.androidSupportRulesVersion}",
        mockitoAndroid : "org.mockito:mockito-android:${libraryVersions.mockitoAndroidVersion}",
        espressoCore   : "com.android.support.test.espresso:espresso-core:${libraryVersions.espressoVersion}",
        espressoIntents: "com.android.support.test.espresso:espresso-intents:${libraryVersions.espressoVersion}",
        espressoContrib: "com.android.support.test.espresso:espresso-contrib:${libraryVersions.espressoVersion}",
        androidRunner  : "com.android.support.test:runner:${libraryVersions.runnerVersion}",
        androidRules   : "com.android.support.test:rules:${libraryVersions.runnerVersion}",
        workMagerTest  : "android.arch.work:work-testing:${libraryVersions.workVersion}",
        jsr310         : "org.threeten:threetenbp:${libraryVersions.java310Version}",
        supportRecyclerView  : "com.android.support:recyclerview-v7:${libraryVersions.supportLibraryVersion}",
]

