apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'

android {

    def androidConfigurationVersion = rootProject.ext.androidVersions

    compileSdkVersion androidConfigurationVersion.androidCompileSdkVersion
    buildToolsVersion androidConfigurationVersion.androidBuildToolsVersion

    defaultConfig {
        minSdkVersion androidConfigurationVersion.androidMinSdkVersion
        targetSdkVersion androidConfigurationVersion.androidTargetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true

        versionCode rootProject.ext.applicationVersionCode
        versionName rootProject.ext.applicationVersionName
    }

    dexOptions {
        preDexLibraries = false
        dexInProcess = false
        javaMaxHeapSize "4g"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        disable 'InvalidPackage'
        disable 'OldTargetApi'
    }
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}

kapt {
    correctErrorTypes = true
}

configurations {
    all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        }
    }
}

androidExtensions {
    experimental = true
}

dependencies {
    def commonDependencies = rootProject.ext.commonDependencies
    def commonTestDependencies = rootProject.ext.commonTestDependencies

    ktlint commonDependencies.ktlint

    implementation project(':common')
    api project(':domain')

    implementation commonDependencies.libs
    implementation commonDependencies.appCore
    implementation commonDependencies.appCoreAdapterKtx

    implementation commonDependencies.supportAnnotations
    implementation commonDependencies.supportV4
    implementation commonDependencies.supportV13
    implementation commonDependencies.supportCompatV7
    implementation commonDependencies.supportRecyclerView
    implementation commonDependencies.supportCardView
    implementation commonDependencies.supportDesign
    implementation commonDependencies.supportvectorDrawable
    implementation commonDependencies.supportConstraint
    implementation commonDependencies.supportCustomTabs
    implementation commonDependencies.multiDex
    implementation commonDependencies.materialDialogs

    implementation commonDependencies.rxKotlin
    implementation commonDependencies.rxAndroid
    implementation commonDependencies.rxPm
    implementation commonDependencies.rxBinding
    implementation commonDependencies.rxNetwork
    implementation commonDependencies.rxPermissions

    implementation commonDependencies.javaxAnnotation
    implementation commonDependencies.javaxInject

    implementation commonDependencies.cicerone
    implementation commonDependencies.pinView

    implementation commonDependencies.expandableLayout
    implementation commonDependencies.tooltipLibrary
    implementation commonDependencies.barcodeScanner
    implementation commonDependencies.materialEditText
    implementation commonDependencies.yandexMapKit
    implementation commonDependencies.cardView
    implementation commonDependencies.pulseView
    implementation commonDependencies.datePicker

    implementation(commonDependencies.work) {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }
    implementation (commonDependencies.rxWork) {
        exclude group: 'com.google.guava', module: 'listenablefuture'
    }

    // Dagger2
    kapt commonDependencies.daggerCompiler
    kapt commonDependencies.daggerAndroidProcessor
    implementation commonDependencies.dagger
    implementation commonDependencies.daggerAndroid
    implementation commonDependencies.daggerAndroidSupport

    implementation commonDependencies.timber
    implementation commonDependencies.jsr310
    implementation commonDependencies.maps
    implementation commonDependencies.inputMask
    implementation(commonDependencies.glide) {
        exclude group: "com.android.support"
    }
    kapt commonDependencies.glideProcessor

    implementation commonDependencies.firebaseCore
    implementation commonDependencies.firebaseMessaging
    implementation commonDependencies.firebaseInAppMessaging
    implementation commonDependencies.firebaseDynamicLinks
    implementation commonDependencies.location

    testImplementation commonTestDependencies.junit
    testImplementation commonTestDependencies.mockito
    testImplementation commonTestDependencies.robolectric
    androidTestImplementation commonTestDependencies.mockitoAndroid
    androidTestImplementation(commonTestDependencies.espressoCore) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestImplementation(commonTestDependencies.androidRunner) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestImplementation(commonTestDependencies.androidRules) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestImplementation(commonTestDependencies.espressoIntents) {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestImplementation(commonTestDependencies.espressoContrib) {
        exclude module: 'appcompat'
        exclude module: 'appcompat-v7'
        exclude module: 'support-v4'
        exclude module: 'support-v13'
        exclude module: 'support-annotations'
        exclude module: 'recyclerview-v7'
        exclude module: 'design'
    }
}
