apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: "io.objectbox"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'


def CREDENTIALS_DEBUG = '../keystore/credentials-debug.properties'
def CREDENTIALS_RELEASE = '../keystore/credentials-release.properties'

def STORE_FILE = 'keystore.file'
def STORE_PASSWORD = 'keystore.password'
def KEY_ALIAS = 'key.alias'
def KEY_PASSWORD = 'key.password'

def GLOBAL_CONFIGURATION_PROPERTIES = "../configuration.properties"
def GLOBAL_CONFIGURATION_APPLICATION_ID = "application.id"

def CI = 'CI'
def LOCAL_PROPERTIES = '../local.properties'
def LOCAL_BUILD_FILE = 'build.file'
def DEFAULT_BUILD_CONFIG_FILE = '../configuration-build-test.properties'
def CONFIG_ENVIRONMENT = 'environment'
def CONFIG_SERVER_URL = 'server.url'
def CONFIG_DEEP_LINK_HOST = 'deep.link.host'
def CONFIG_APP_ID_SUFFIX = 'app.id.suffix'
def CONFIG_APP_NAME_SUFFIX = 'app.name.suffix'
def CONFIG_LOG_ENABLED = 'log.enabled'

android {

    def globalConfigProperties = new Properties()
    file(GLOBAL_CONFIGURATION_PROPERTIES).withInputStream {
        globalConfigProperties.load(it)
    }

    def appId = globalConfigProperties[GLOBAL_CONFIGURATION_APPLICATION_ID]

    def buildConfigFile

    def ci = System.getenv(CI)
    if (ci != null) {
        println("Build runned on ${ci} CI server.")
        def configFilePropertyName = "${appId}.config.file".toUpperCase().replace(".", "_")
        buildConfigFile = System.getenv(configFilePropertyName)

        if (buildConfigFile == null) {
            println("There is not environment variable ${configFilePropertyName}, default value will be used.")
            buildConfigFile = DEFAULT_BUILD_CONFIG_FILE
        }
    } else {
        println("Build runned on local machine.")
        def localProperties = new Properties()
        file(LOCAL_PROPERTIES).withInputStream {
            localProperties.load(it)
        }
        buildConfigFile = localProperties[LOCAL_BUILD_FILE]

        if (buildConfigFile == null) {
            println("There is property ${LOCAL_BUILD_FILE} at ${LOCAL_PROPERTIES}, default value will be used.")
            buildConfigFile = DEFAULT_BUILD_CONFIG_FILE
        }
    }

    println("Build config will be loaded from: ${buildConfigFile}.")

    def buildConfigProperties = new Properties()
    file(buildConfigFile).withInputStream {
        buildConfigProperties.load(it)
    }

    def androidConfigurationVersion = rootProject.ext.androidVersions

    compileSdkVersion androidConfigurationVersion.androidCompileSdkVersion
    buildToolsVersion androidConfigurationVersion.androidBuildToolsVersion

    defaultConfig {
        applicationId appId
        minSdkVersion androidConfigurationVersion.androidMinSdkVersion
        targetSdkVersion androidConfigurationVersion.androidTargetSdkVersion

        versionCode rootProject.ext.applicationVersionCode
        versionName rootProject.ext.applicationVersionName

        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {

        def credentialsDebug = new Properties()
        file(CREDENTIALS_DEBUG).withInputStream {
            credentialsDebug.load(it)
        }

        debug {
            storeFile file(credentialsDebug[STORE_FILE])
            storePassword credentialsDebug[STORE_PASSWORD]
            keyAlias credentialsDebug[KEY_ALIAS]
            keyPassword credentialsDebug[KEY_PASSWORD]
        }

        release {
            def credentialsRelease = new Properties()
            def credentialsReleaseFile = file(CREDENTIALS_RELEASE)
            if (credentialsReleaseFile.exists()) {
                credentialsReleaseFile.withInputStream { credentialsRelease.load(it) }
                println("credentials-release.properties is exist")
            } else {
                println("credentials-release.properties isn't exist - credentials-debug.properties will be used")
                credentialsRelease = credentialsDebug
            }

            storeFile file(credentialsRelease[STORE_FILE])
            storePassword credentialsRelease[STORE_PASSWORD]
            keyAlias credentialsRelease[KEY_ALIAS]
            keyPassword credentialsRelease[KEY_PASSWORD]
        }
    }

    buildTypes {

        all {
            ext.betaDistributionReleaseNotesFilePath =
                    file('../BUILD_NOTES.md').absolutePath
            ext.betaDistributionGroupAliases = "QA-Nullgr"

            def appIdSuffix = buildConfigProperties[CONFIG_APP_ID_SUFFIX]
            if (appIdSuffix != null) {
                applicationIdSuffix ".${appIdSuffix}"
            }

            def appNameSuffix = buildConfigProperties[CONFIG_APP_NAME_SUFFIX]
            if (appNameSuffix != null) {
                versionNameSuffix "-${appNameSuffix}"
            }

            buildConfigField "String", "ENVIRONMENT", "\"${buildConfigProperties[CONFIG_ENVIRONMENT]}\""
            buildConfigField "String", "SERVER_URL", "\"${buildConfigProperties[CONFIG_SERVER_URL]}\""
            buildConfigField "boolean", "IS_LOG_ENABLED", buildConfigProperties[CONFIG_LOG_ENABLED]

            resValue "string", "app_deep_link_host", buildConfigProperties[CONFIG_DEEP_LINK_HOST]
        }

        debug {
            signingConfig signingConfigs.debug
        }

        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            proguardFiles fileTree('proguard').asList().toArray()
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        disable 'InvalidPackage'
        disable 'OldTargetApi'
    }
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }

    splits {
        abi {
            enable true
            reset()
            include "x86", "x86_64", "armeabi-v7a", "arm64-v8a"
            universalApk true
        }
    }
    buildFeatures {
        viewBinding = true
    }
}

kapt {
    correctErrorTypes = true
    javacOptions {
        option("-source", "8")
        option("-target", "8")
    }
}

configurations {
    all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        }
    }
}

android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        // Filter is null for universal APKs.
        def filter = output.getFilter(com.android.build.OutputFile.ABI)

        if (filter == null) {
            tasks.findAll {
                it.name.startsWith("crashlyticsUploadDistribution${variant.name.capitalize()}")
            }.each {
                it.doFirst {
                    ext.betaDistributionApkFilePath = output.outputFile.absolutePath
                }
            }
        }
    }
}


dependencies {
    def commonDependencies = rootProject.ext.commonDependencies
    def commonTestDependencies = rootProject.ext.commonTestDependencies

    implementation project(':core-all')
    implementation project(':core-security')
    implementation project(':core-rx')
    implementation project(':core-resources')
    implementation project(':core-adapter')
    implementation project(':core-hardware')
    implementation project(':core-preferences')
    implementation project(':core-interactor')
    implementation project(':common')
    api project(':presentation')
    api project(':data')

    implementation commonDependencies.libs

    implementation commonDependencies.materialDesign

    implementation commonDependencies.androidxMultidex

    implementation commonDependencies.googleFit
    implementation commonDependencies.googleAuth
    implementation commonDependencies.materialDialogs
    implementation commonDependencies.yandexMapKit
    implementation commonDependencies.cardView
    implementation commonDependencies.pulseView

    implementation commonDependencies.rxKotlin
    implementation commonDependencies.rxAndroid
    implementation commonDependencies.rxPm
    implementation commonDependencies.rxBinding
    implementation commonDependencies.rxNetwork
    implementation commonDependencies.rxPermissions

    implementation commonDependencies.javaxAnnotation
    implementation commonDependencies.javaxInject

    implementation commonDependencies.cicerone
    implementation commonDependencies.pinView

    implementation commonDependencies.expandableLayout
    implementation commonDependencies.tooltipLibrary
    implementation commonDependencies.rxBluetooth

    // Dagger2
    kapt commonDependencies.daggerCompiler
    kapt commonDependencies.daggerAndroidProcessor
    implementation commonDependencies.dagger
    implementation commonDependencies.daggerAndroid
    implementation commonDependencies.daggerAndroidSupport

    implementation commonDependencies.timber
    implementation commonDependencies.jsr310
    implementation commonDependencies.maps
    implementation commonDependencies.inputMask

    implementation commonDependencies.retrofit
    implementation commonDependencies.retrofitConverter
    implementation commonDependencies.retrofitAdapter
    implementation commonDependencies.okHttp
    implementation commonDependencies.okHttpLogger
    implementation commonDependencies.gson

    implementation platform(commonDependencies.firebaseBom)
    implementation commonDependencies.firebaseMessaging
    implementation commonDependencies.firebaseCrashlytics
    implementation commonDependencies.firebaseAnalytics
    implementation commonDependencies.location
    implementation commonDependencies.datePicker

    implementation commonDependencies.nordicScanner

    implementation commonDependencies.guavaConflictLost

    testImplementation commonTestDependencies.junit
    testImplementation commonTestDependencies.mockito
}
