apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {

    def androidConfigurationVersion = rootProject.ext.androidVersions

    compileSdkVersion androidConfigurationVersion.androidCompileSdkVersion
    buildToolsVersion androidConfigurationVersion.androidBuildToolsVersion

    defaultConfig {
        minSdkVersion androidConfigurationVersion.androidMinSdkVersion
        targetSdkVersion androidConfigurationVersion.androidTargetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        disable 'InvalidPackage'
        disable 'OldTargetApi'
    }
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}

configurations {
    all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        }
    }
}

dependencies {
    def commonDependencies = rootProject.ext.commonDependencies
    def commonTestDependencies = rootProject.ext.commonTestDependencies

    ktlint commonDependencies.ktlint

    implementation project(':core-interactor')

//    implementation commonDependencies.appCoreInteractor

    implementation commonDependencies.rxKotlin

    implementation commonDependencies.javaxAnnotation
    implementation commonDependencies.javaxInject

    implementation commonDependencies.timber
    implementation commonDependencies.jsr310

    testImplementation commonTestDependencies.junit
    testImplementation commonTestDependencies.mockito
}
