apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'io.objectbox'

android {

    def androidConfigurationVersion = rootProject.ext.androidVersions

    compileSdkVersion androidConfigurationVersion.androidCompileSdkVersion
    buildToolsVersion androidConfigurationVersion.androidBuildToolsVersion

    defaultConfig {
        minSdkVersion androidConfigurationVersion.androidMinSdkVersion
        targetSdkVersion androidConfigurationVersion.androidTargetSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        disable 'InvalidPackage'
        disable 'OldTargetApi'
    }
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}

configurations {
    all {
        resolutionStrategy {
            force "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        }
    }
}

kapt {
    javacOptions {
        option("-source", "8")
        option("-target", "8")
    }
}

dependencies {
    def commonDependencies = rootProject.ext.commonDependencies
    def commonTestDependencies = rootProject.ext.commonTestDependencies

    implementation project(':core-rx')
    implementation project(':core-security')
    implementation project(':core-hardware')
    implementation project(':core-intents')
    implementation project(':core-preferences')
    implementation project(':common')
    api project(':domain')

    implementation commonDependencies.googleFit
    implementation commonDependencies.googleAuth

    implementation commonDependencies.rxKotlin
    implementation commonDependencies.rxNetwork

    implementation commonDependencies.javaxAnnotation
    implementation commonDependencies.javaxInject

    // Dagger2
    kapt commonDependencies.daggerCompiler
    kapt commonDependencies.daggerAndroidProcessor
    implementation commonDependencies.dagger
    implementation commonDependencies.daggerAndroid
    implementation commonDependencies.daggerAndroidSupport

    implementation commonDependencies.timber

    implementation commonDependencies.retrofit
    implementation commonDependencies.retrofitConverter
    implementation commonDependencies.retrofitAdapter
    implementation commonDependencies.okHttp
    implementation commonDependencies.okHttpLogger
    implementation commonDependencies.gson

    implementation commonDependencies.fb
    implementation commonDependencies.vk
    implementation commonDependencies.ok

    implementation commonDependencies.objectbox
    implementation commonDependencies.jsr310

    implementation commonDependencies.nordicScanner
    implementation commonDependencies.nordicDfu
    implementation commonDependencies.rxBluetooth
    implementation commonDependencies.rxReplaying

    implementation 'org.greenrobot:essentials:3.1.0'

    testImplementation commonTestDependencies.junit
    testImplementation commonTestDependencies.mockito
}
